//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.NBRMServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://www.nbrm.mk/klservice/", ConfigurationName="NBRMServiceReference.KursSoap")]
    public interface KursSoap {
        
        // CODEGEN: Generating message contract since element name GetExchangeRateDResult from namespace https://www.nbrm.mk/klservice/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://www.nbrm.mk/klservice/GetExchangeRateD", ReplyAction="*")]
        WindowsFormsApp1.NBRMServiceReference.GetExchangeRateDResponse GetExchangeRateD(WindowsFormsApp1.NBRMServiceReference.GetExchangeRateDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.nbrm.mk/klservice/GetExchangeRateD", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.NBRMServiceReference.GetExchangeRateDResponse> GetExchangeRateDAsync(WindowsFormsApp1.NBRMServiceReference.GetExchangeRateDRequest request);
        
        // CODEGEN: Generating message contract since element name StartDate from namespace https://www.nbrm.mk/klservice/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://www.nbrm.mk/klservice/GetExchangeRate", ReplyAction="*")]
        WindowsFormsApp1.NBRMServiceReference.GetExchangeRateResponse GetExchangeRate(WindowsFormsApp1.NBRMServiceReference.GetExchangeRateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.nbrm.mk/klservice/GetExchangeRate", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.NBRMServiceReference.GetExchangeRateResponse> GetExchangeRateAsync(WindowsFormsApp1.NBRMServiceReference.GetExchangeRateRequest request);
        
        // CODEGEN: Generating message contract since element name GetExchangeRatesDResult from namespace https://www.nbrm.mk/klservice/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://www.nbrm.mk/klservice/GetExchangeRatesD", ReplyAction="*")]
        WindowsFormsApp1.NBRMServiceReference.GetExchangeRatesDResponse GetExchangeRatesD(WindowsFormsApp1.NBRMServiceReference.GetExchangeRatesDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.nbrm.mk/klservice/GetExchangeRatesD", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.NBRMServiceReference.GetExchangeRatesDResponse> GetExchangeRatesDAsync(WindowsFormsApp1.NBRMServiceReference.GetExchangeRatesDRequest request);
        
        // CODEGEN: Generating message contract since element name StartDate from namespace https://www.nbrm.mk/klservice/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://www.nbrm.mk/klservice/GetExchangeRates", ReplyAction="*")]
        WindowsFormsApp1.NBRMServiceReference.GetExchangeRatesResponse GetExchangeRates(WindowsFormsApp1.NBRMServiceReference.GetExchangeRatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.nbrm.mk/klservice/GetExchangeRates", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp1.NBRMServiceReference.GetExchangeRatesResponse> GetExchangeRatesAsync(WindowsFormsApp1.NBRMServiceReference.GetExchangeRatesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExchangeRateDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExchangeRateD", Namespace="https://www.nbrm.mk/klservice/", Order=0)]
        public WindowsFormsApp1.NBRMServiceReference.GetExchangeRateDRequestBody Body;
        
        public GetExchangeRateDRequest() {
        }
        
        public GetExchangeRateDRequest(WindowsFormsApp1.NBRMServiceReference.GetExchangeRateDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.nbrm.mk/klservice/")]
    public partial class GetExchangeRateDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime StartDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime EndDate;
        
        public GetExchangeRateDRequestBody() {
        }
        
        public GetExchangeRateDRequestBody(System.DateTime StartDate, System.DateTime EndDate) {
            this.StartDate = StartDate;
            this.EndDate = EndDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExchangeRateDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExchangeRateDResponse", Namespace="https://www.nbrm.mk/klservice/", Order=0)]
        public WindowsFormsApp1.NBRMServiceReference.GetExchangeRateDResponseBody Body;
        
        public GetExchangeRateDResponse() {
        }
        
        public GetExchangeRateDResponse(WindowsFormsApp1.NBRMServiceReference.GetExchangeRateDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.nbrm.mk/klservice/")]
    public partial class GetExchangeRateDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetExchangeRateDResult;
        
        public GetExchangeRateDResponseBody() {
        }
        
        public GetExchangeRateDResponseBody(string GetExchangeRateDResult) {
            this.GetExchangeRateDResult = GetExchangeRateDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExchangeRateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExchangeRate", Namespace="https://www.nbrm.mk/klservice/", Order=0)]
        public WindowsFormsApp1.NBRMServiceReference.GetExchangeRateRequestBody Body;
        
        public GetExchangeRateRequest() {
        }
        
        public GetExchangeRateRequest(WindowsFormsApp1.NBRMServiceReference.GetExchangeRateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.nbrm.mk/klservice/")]
    public partial class GetExchangeRateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StartDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string EndDate;
        
        public GetExchangeRateRequestBody() {
        }
        
        public GetExchangeRateRequestBody(string StartDate, string EndDate) {
            this.StartDate = StartDate;
            this.EndDate = EndDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExchangeRateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExchangeRateResponse", Namespace="https://www.nbrm.mk/klservice/", Order=0)]
        public WindowsFormsApp1.NBRMServiceReference.GetExchangeRateResponseBody Body;
        
        public GetExchangeRateResponse() {
        }
        
        public GetExchangeRateResponse(WindowsFormsApp1.NBRMServiceReference.GetExchangeRateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.nbrm.mk/klservice/")]
    public partial class GetExchangeRateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetExchangeRateResult;
        
        public GetExchangeRateResponseBody() {
        }
        
        public GetExchangeRateResponseBody(string GetExchangeRateResult) {
            this.GetExchangeRateResult = GetExchangeRateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExchangeRatesDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExchangeRatesD", Namespace="https://www.nbrm.mk/klservice/", Order=0)]
        public WindowsFormsApp1.NBRMServiceReference.GetExchangeRatesDRequestBody Body;
        
        public GetExchangeRatesDRequest() {
        }
        
        public GetExchangeRatesDRequest(WindowsFormsApp1.NBRMServiceReference.GetExchangeRatesDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.nbrm.mk/klservice/")]
    public partial class GetExchangeRatesDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime StartDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime EndDate;
        
        public GetExchangeRatesDRequestBody() {
        }
        
        public GetExchangeRatesDRequestBody(System.DateTime StartDate, System.DateTime EndDate) {
            this.StartDate = StartDate;
            this.EndDate = EndDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExchangeRatesDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExchangeRatesDResponse", Namespace="https://www.nbrm.mk/klservice/", Order=0)]
        public WindowsFormsApp1.NBRMServiceReference.GetExchangeRatesDResponseBody Body;
        
        public GetExchangeRatesDResponse() {
        }
        
        public GetExchangeRatesDResponse(WindowsFormsApp1.NBRMServiceReference.GetExchangeRatesDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.nbrm.mk/klservice/")]
    public partial class GetExchangeRatesDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetExchangeRatesDResult;
        
        public GetExchangeRatesDResponseBody() {
        }
        
        public GetExchangeRatesDResponseBody(string GetExchangeRatesDResult) {
            this.GetExchangeRatesDResult = GetExchangeRatesDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExchangeRatesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExchangeRates", Namespace="https://www.nbrm.mk/klservice/", Order=0)]
        public WindowsFormsApp1.NBRMServiceReference.GetExchangeRatesRequestBody Body;
        
        public GetExchangeRatesRequest() {
        }
        
        public GetExchangeRatesRequest(WindowsFormsApp1.NBRMServiceReference.GetExchangeRatesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.nbrm.mk/klservice/")]
    public partial class GetExchangeRatesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StartDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string EndDate;
        
        public GetExchangeRatesRequestBody() {
        }
        
        public GetExchangeRatesRequestBody(string StartDate, string EndDate) {
            this.StartDate = StartDate;
            this.EndDate = EndDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExchangeRatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExchangeRatesResponse", Namespace="https://www.nbrm.mk/klservice/", Order=0)]
        public WindowsFormsApp1.NBRMServiceReference.GetExchangeRatesResponseBody Body;
        
        public GetExchangeRatesResponse() {
        }
        
        public GetExchangeRatesResponse(WindowsFormsApp1.NBRMServiceReference.GetExchangeRatesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://www.nbrm.mk/klservice/")]
    public partial class GetExchangeRatesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetExchangeRatesResult;
        
        public GetExchangeRatesResponseBody() {
        }
        
        public GetExchangeRatesResponseBody(string GetExchangeRatesResult) {
            this.GetExchangeRatesResult = GetExchangeRatesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface KursSoapChannel : WindowsFormsApp1.NBRMServiceReference.KursSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KursSoapClient : System.ServiceModel.ClientBase<WindowsFormsApp1.NBRMServiceReference.KursSoap>, WindowsFormsApp1.NBRMServiceReference.KursSoap {
        
        public KursSoapClient() {
        }
        
        public KursSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KursSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KursSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KursSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.NBRMServiceReference.GetExchangeRateDResponse WindowsFormsApp1.NBRMServiceReference.KursSoap.GetExchangeRateD(WindowsFormsApp1.NBRMServiceReference.GetExchangeRateDRequest request) {
            return base.Channel.GetExchangeRateD(request);
        }
        
        public string GetExchangeRateD(System.DateTime StartDate, System.DateTime EndDate) {
            WindowsFormsApp1.NBRMServiceReference.GetExchangeRateDRequest inValue = new WindowsFormsApp1.NBRMServiceReference.GetExchangeRateDRequest();
            inValue.Body = new WindowsFormsApp1.NBRMServiceReference.GetExchangeRateDRequestBody();
            inValue.Body.StartDate = StartDate;
            inValue.Body.EndDate = EndDate;
            WindowsFormsApp1.NBRMServiceReference.GetExchangeRateDResponse retVal = ((WindowsFormsApp1.NBRMServiceReference.KursSoap)(this)).GetExchangeRateD(inValue);
            return retVal.Body.GetExchangeRateDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.NBRMServiceReference.GetExchangeRateDResponse> WindowsFormsApp1.NBRMServiceReference.KursSoap.GetExchangeRateDAsync(WindowsFormsApp1.NBRMServiceReference.GetExchangeRateDRequest request) {
            return base.Channel.GetExchangeRateDAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.NBRMServiceReference.GetExchangeRateDResponse> GetExchangeRateDAsync(System.DateTime StartDate, System.DateTime EndDate) {
            WindowsFormsApp1.NBRMServiceReference.GetExchangeRateDRequest inValue = new WindowsFormsApp1.NBRMServiceReference.GetExchangeRateDRequest();
            inValue.Body = new WindowsFormsApp1.NBRMServiceReference.GetExchangeRateDRequestBody();
            inValue.Body.StartDate = StartDate;
            inValue.Body.EndDate = EndDate;
            return ((WindowsFormsApp1.NBRMServiceReference.KursSoap)(this)).GetExchangeRateDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.NBRMServiceReference.GetExchangeRateResponse WindowsFormsApp1.NBRMServiceReference.KursSoap.GetExchangeRate(WindowsFormsApp1.NBRMServiceReference.GetExchangeRateRequest request) {
            return base.Channel.GetExchangeRate(request);
        }
        
        public string GetExchangeRate(string StartDate, string EndDate) {
            WindowsFormsApp1.NBRMServiceReference.GetExchangeRateRequest inValue = new WindowsFormsApp1.NBRMServiceReference.GetExchangeRateRequest();
            inValue.Body = new WindowsFormsApp1.NBRMServiceReference.GetExchangeRateRequestBody();
            inValue.Body.StartDate = StartDate;
            inValue.Body.EndDate = EndDate;
            WindowsFormsApp1.NBRMServiceReference.GetExchangeRateResponse retVal = ((WindowsFormsApp1.NBRMServiceReference.KursSoap)(this)).GetExchangeRate(inValue);
            return retVal.Body.GetExchangeRateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.NBRMServiceReference.GetExchangeRateResponse> WindowsFormsApp1.NBRMServiceReference.KursSoap.GetExchangeRateAsync(WindowsFormsApp1.NBRMServiceReference.GetExchangeRateRequest request) {
            return base.Channel.GetExchangeRateAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.NBRMServiceReference.GetExchangeRateResponse> GetExchangeRateAsync(string StartDate, string EndDate) {
            WindowsFormsApp1.NBRMServiceReference.GetExchangeRateRequest inValue = new WindowsFormsApp1.NBRMServiceReference.GetExchangeRateRequest();
            inValue.Body = new WindowsFormsApp1.NBRMServiceReference.GetExchangeRateRequestBody();
            inValue.Body.StartDate = StartDate;
            inValue.Body.EndDate = EndDate;
            return ((WindowsFormsApp1.NBRMServiceReference.KursSoap)(this)).GetExchangeRateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.NBRMServiceReference.GetExchangeRatesDResponse WindowsFormsApp1.NBRMServiceReference.KursSoap.GetExchangeRatesD(WindowsFormsApp1.NBRMServiceReference.GetExchangeRatesDRequest request) {
            return base.Channel.GetExchangeRatesD(request);
        }
        
        public string GetExchangeRatesD(System.DateTime StartDate, System.DateTime EndDate) {
            WindowsFormsApp1.NBRMServiceReference.GetExchangeRatesDRequest inValue = new WindowsFormsApp1.NBRMServiceReference.GetExchangeRatesDRequest();
            inValue.Body = new WindowsFormsApp1.NBRMServiceReference.GetExchangeRatesDRequestBody();
            inValue.Body.StartDate = StartDate;
            inValue.Body.EndDate = EndDate;
            WindowsFormsApp1.NBRMServiceReference.GetExchangeRatesDResponse retVal = ((WindowsFormsApp1.NBRMServiceReference.KursSoap)(this)).GetExchangeRatesD(inValue);
            return retVal.Body.GetExchangeRatesDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.NBRMServiceReference.GetExchangeRatesDResponse> WindowsFormsApp1.NBRMServiceReference.KursSoap.GetExchangeRatesDAsync(WindowsFormsApp1.NBRMServiceReference.GetExchangeRatesDRequest request) {
            return base.Channel.GetExchangeRatesDAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.NBRMServiceReference.GetExchangeRatesDResponse> GetExchangeRatesDAsync(System.DateTime StartDate, System.DateTime EndDate) {
            WindowsFormsApp1.NBRMServiceReference.GetExchangeRatesDRequest inValue = new WindowsFormsApp1.NBRMServiceReference.GetExchangeRatesDRequest();
            inValue.Body = new WindowsFormsApp1.NBRMServiceReference.GetExchangeRatesDRequestBody();
            inValue.Body.StartDate = StartDate;
            inValue.Body.EndDate = EndDate;
            return ((WindowsFormsApp1.NBRMServiceReference.KursSoap)(this)).GetExchangeRatesDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.NBRMServiceReference.GetExchangeRatesResponse WindowsFormsApp1.NBRMServiceReference.KursSoap.GetExchangeRates(WindowsFormsApp1.NBRMServiceReference.GetExchangeRatesRequest request) {
            return base.Channel.GetExchangeRates(request);
        }
        
        public string GetExchangeRates(string StartDate, string EndDate) {
            WindowsFormsApp1.NBRMServiceReference.GetExchangeRatesRequest inValue = new WindowsFormsApp1.NBRMServiceReference.GetExchangeRatesRequest();
            inValue.Body = new WindowsFormsApp1.NBRMServiceReference.GetExchangeRatesRequestBody();
            inValue.Body.StartDate = StartDate;
            inValue.Body.EndDate = EndDate;
            WindowsFormsApp1.NBRMServiceReference.GetExchangeRatesResponse retVal = ((WindowsFormsApp1.NBRMServiceReference.KursSoap)(this)).GetExchangeRates(inValue);
            return retVal.Body.GetExchangeRatesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.NBRMServiceReference.GetExchangeRatesResponse> WindowsFormsApp1.NBRMServiceReference.KursSoap.GetExchangeRatesAsync(WindowsFormsApp1.NBRMServiceReference.GetExchangeRatesRequest request) {
            return base.Channel.GetExchangeRatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.NBRMServiceReference.GetExchangeRatesResponse> GetExchangeRatesAsync(string StartDate, string EndDate) {
            WindowsFormsApp1.NBRMServiceReference.GetExchangeRatesRequest inValue = new WindowsFormsApp1.NBRMServiceReference.GetExchangeRatesRequest();
            inValue.Body = new WindowsFormsApp1.NBRMServiceReference.GetExchangeRatesRequestBody();
            inValue.Body.StartDate = StartDate;
            inValue.Body.EndDate = EndDate;
            return ((WindowsFormsApp1.NBRMServiceReference.KursSoap)(this)).GetExchangeRatesAsync(inValue);
        }
    }
}
